### ISSUE TITLE
Docker does not recreate the container

### ISSUE THREAD

**Issue by DavidSchmidt1** [Mobility-Data-Space/Deployment-Examples#3]
### Subject of the issue
Docker Compose is ignoring the changes made to config.json

### Your environment
* Ubuntu 20.04.5 LTS
* Docker version 20.10.18

### Steps to reproduce

Initial build of an IDS Connector (first building works as excpected)

Change URL in config.json under:

"@type": "ids:BaseConnector",
"@id": "https://xxx.new.test.com"

Clean Docker:
1. docker stop `docker ps -qa`
2. docker rm `docker ps -qa`
3. docker rmi -f `docker images -qa `
4. docker system prune --all
5. cd /Deployment-Examples/docker-test-environment
6. docker-compose up --force-recreate

Navigate to http://localhost:8083/

### Expected behaviour
Seeing the new URL https://xxx.new.test.com

### Actual behaviour
Seeing the old URL https://xxx.old.test.com

in combination with this error code 
`ERROR - PRODUCTIVE_DEPLOYMENT: No IDS-Message sent! No DAT could be acquired from DAPS! [code=(IMSCOE0001), reason=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): Unexpected code Response{protocol=h2, code=400, message=, url=https://daps.test.mobility-dataspace.eu/token} Body: {"error":"invalid_client","error_description":"Client unknown"})] `

**Comment by SebastianOpriel** [comment]
It seems like that the volumes were not deleted with your commands. DSC caches the configuration in its database. You may solve the issue by removing the volumes with `docker-compose down -v`.

Generally, there would be the way to force reloading the configuration via additional environment variable `CONFIGURATION_FORCE_RELOAD=TRUE`, but there seems to be a bug not overwriting database values.

**Comment by DavidSchmidt1** [comment]
Thanks for your input! We are now able to change the settings. 
We still facing a problem with receiving Data though. I will open a seperat issue for that.
