### ISSUE TITLE
Can't download own offering

### ISSUE THREAD

**Issue by JesoosSoz** [Mobility-Data-Space/Deployment-Examples#4]
After offering an image in the offering tab and finding it on the request tab, I am not able to request or download the resource.

### Environment
* Version 1.2.0 or 1.1.0 of the GitHub Repository
* Docker version 20.10.18
* Ubuntu 20.04.5 LTS

### Steps to reproduce
1. Changing the keystore.p12
2. Changing in the config.json "ids:maintainer", "ids:curator", "ids:title@value", "ids:accessURL@id" and "ids:connectorDescription@id"
3. Setting SPRING_FLYWAY_ENABLED=false (In the 1.2.0 Version)
4. Execute docker-compose up
5. Going to localhost:8083
6. Offering an image and register it with the broker https://broker.test.mobility-dataspace.eu/infrastructure
7. Going to the request tab and search for the offering with the broker https://broker.test.mobility-dataspace.eu/infrastructure
8. Finding the resource and click on "request resource"

### Expected behaviour
I can request my own image and download it

### Actual behaviour
An error message appears in the console and in the UI shows an error message
![Fehler2](https://user-images.githubusercontent.com/39771284/196209817-22f31c58-e249-413a-b898-a1e061addbc1.png)
![Fehler1](https://user-images.githubusercontent.com/39771284/196209821-2f3f50ef-8e0a-42de-93f7-092b9852225c.png)

**Comment by SebastianOpriel** [comment]
To me, it seems to be related to you infrastructure setup, as the HTTP request doesn't reach a valid endpoint. Can you clarify on:
- [ ] With image, you mean a file of type jpeg (mime type `image/jpeg`)
- [ ] On the dashboard it shows the correct URL with `/api/ids/data` suffix?
- [ ] Can you access the URL from dashboard manually via the browser? (shall give you a HTTP 405)

**Comment by JesoosSoz** [comment]
- Yes, I'm using image/png
- Yes, it shows the correct URL
- Yes, and I receive a 405, but only with https, and it immediately switches to no https.
![nohttp](https://user-images.githubusercontent.com/39771284/198574604-f31eb5ec-cfe8-45ab-b918-6e1c2a89dd01.png)

I tested 3 Scenarios for the URL in the Dashboard:
1. With Https/Http and without a port in the URL:
![OfferingBug2](https://user-images.githubusercontent.com/39771284/198573924-5f43f2c7-fd04-44e8-abad-b4a91ac55f14.png)
2. With Https and with port 8080 in the URL:
![OfferingBug3](https://user-images.githubusercontent.com/39771284/198573967-2b3aca35-4ea9-48ec-809c-2d5102c3dd09.png)
3. With Http and with port 8080 in the URL;
![OfferingBug4](https://user-images.githubusercontent.com/39771284/198574013-ab00cd20-6f66-4aac-9db0-b84ac5e3fdbb.png)

**Comment by SebastianOpriel** [comment]
> Yes, and I receive a 405, but only with https, and it immediately switches to no https.

It seems to me, that there might be some issue with your TLS configuration, as a switch is not intended. I would recommend to try following: disable ssl of connector itself (SERVER_SSL_ENABLED=false) and use a reverse proxy of your infrastructure which serves a TLS encryption.

For curiosity: You added your TLS private key for your domain to the keystore.p12 (with another alias) and set it correctly (SERVER_SSL_KEY-ALIAS=YOUR_DOMAIN_ALIAS)?

**Comment by JesoosSoz** [comment]
> For curiosity: You added your TLS private key for your domain to the keystore.p12 (with another alias) and set it correctly (SERVER_SSL_KEY-ALIAS=YOUR_DOMAIN_ALIAS)?

I exchanged the p12 file from the folder with the p12 file from the zipped folder (with crt, p12 and key file) and renamed it, like described in the tutorial: https://github.com/Mobility-Data-Space/mobility-data-space/wiki/2.-Step-(Configuration)
I didn't change the SERVER_SSL_KEY property.

**Comment by SebastianOpriel** [comment]
So, if you host the connector on a publicly available infrastructure like azure, you need to take care of proper TLS certificates for the domain you are using. The X509 certificate you receive is for IDS identification. Indeed, this is not explained well in the tutorial. As said, you could disable SSL in the connector and take care for http and TLS exncryption in your infrastructure

**Comment by JesoosSoz** [comment]
> So, if you host the connector on a publicly available infrastructure like azure, you need to take care of proper TLS certificates for the domain you are using. The X509 certificate you receive is for IDS identification. Indeed, this is not explained well in the tutorial.

Do I understand correctly that the provided X509 certificate is not used for the TLS Encryption and I need to provide one separately, even without using a reverse proxy? 

> As said, you could disable SSL in the connector and take care for http and TLS exncryption in your infrastructure

Is it necessary, or are there other options?

**Comment by SebastianOpriel** [comment]
Dear @JesoosSoz please have a look at release 2.0.0. We split up TLS and IDS certificate. You need to take your MDS certificate and use it as keystore_ids.p12. A keystore_tls.p12 for TLS is added with a self-signed certificate for localhost. 

> Do I understand correctly that the provided X509 certificate is not used for the TLS Encryption and I need to provide one separately, even without using a reverse proxy?
You need to care yourself about TLS encryption. The supplied keystore_tls.p12 is just an example. Either you can issue a certificate (e.g. letsencrypt) and mount it as keystore_tls.p12 (exposing the connector directly) or you could disable SSL and use a reverse proxy, which needs to take care of TLS. If you are unsure how to configure your infrastructure, please consult someone of your company with experience in rolling out hosted applications.
